### PR TITLE
curses is part of the standard library

### PR DESCRIPTION
**Pull request by joy-rosie**
https://docs.python.org/3.8/library/curses.html

### CODE REVIEW

**Comment by clvnkhr** [comment]
at this point im scared to open the code lmao did i even import curses

**Comment by clvnkhr** [comment]
One reason I added that comment is that you couldnt get flap.py running last time in windows, and I think windows python doesn't include curses. Is that still the case? I see that there are things like https://pypi.org/project/windows-curses/ now anyhow

**Comment by joy-rosie** [comment]
I don't know since which version but I think in all the latest ones (3.6+) it is in standard library. Although... I am on Linux so it might be that for windows you still need to install it...

**Comment by clvnkhr** [comment]
I'll merge it and allow the hypothetical noob who finds this to struggle getting it to run :P

**Pull request merged**
